### PR TITLE
Change name and upgrading dependencies

### LINKED ISSUE #356: Update packages
Look for updates for package.json, bower.json and composer.json

### LINKED ISSUE #357: Change company name
Change company name to Xtendify Technologies
Replace references to Sure Swift Capital or Moon Stone with Xtendify

### PR DESCRIPTION
**Pull request by rosinghal**
- [x] Change the company name and URLs to resolve #357
- [x] Upgrade composer and npm dependencies to resolve #356

### CODE REVIEW

**Comment by nickyoung87** [comment]
image

@rosinghal Kind of seems like a slap in the face to remove the original creators and contributors of the plugin don't you think?

**Comment by rosinghal** [comment]
@nickyoung87 I agree with you on this, let me know if the new changes look good.

Also, would it be possible for you to review the PR? Asking you since I am still not sure I have wrapped my head around `php-scoper` yet and you reviewed https://github.com/Xtendify/Simple-Calendar/pull/342.

**Comment by nickyoung87** [comment]
@rosinghal Hey thanks I really appreciate you keeping us in there!

I was about to go to bed, but I should have some time tomorrow to give a glance at that and hopefully help answer any questions!

**Comment by nickyoung87** [comment]
@rosinghal So PHP Scoper is a tool that makes the project namespace itself. This is important because if 2 WordPress plugins are installed with different versions of the same package then it will be a race condition for which one gets loaded. PHP Scoper just tries to resolve that issue.

I hope that clears that part up a little, but let me know. As for the PR review, are you speaking of this current PR or another one?

**Comment by rosinghal** [comment]
@nickyoung87 understood, this PR please, yeah

**Comment by rosinghal** [comment]
@Akhill2020 please review. I have reverted the version of google/apiclient-services so there won't be any update required of namespaces related to Google.

**Comment by nickyoung87** [comment]
@rosinghal I finally looked this over. I think it looks good. It's mostly just small changes to use the new company name from what I can tell. I think it was a good idea to add an `npm run setup` and `npm run dev` command too.

I would assume you are testing it works locally, so if it passes in a local install it should work from the repo.

Hope that helps!

**Pull request merged**
