### PR TITLE
Some Simple calendar improvements

### PR DESCRIPTION
**Pull request by sarjona**
First of all, thanks for your plugin. We're using it in some of our projects :-)

We've fixed some bugs and included some improvements. We would like to share with you them:

- By default, exclude grouped calendars from get_calendars function and Remove taxonomies associated to grouped calendar for preventing errors
This 2 patches are necessary to avoid deadlock when users add a grouped calendar to a category or when users add a grouped calendar to another grouped calendar (which contains the first one).

- Load localization file
Without this patch, we're not able to load the catalan .po file.

- Show event information on mouse over
It's an improvement to simulate a behaviour in the Google calendar events legacy version. With this patch, events information is showed on mouse over (it's not necessary to click).

### CODE REVIEW

**Comment by nickyoung87** [comment]
Thank you for your time and submitting a PR. I haven't looked over everything yet, but something did stick out to me so I want to ask about it. The hover feature you mentioned - is that not the same as this setting? 

http://www.screencast.com/t/9Kfjy3Sg2Nm

**Comment by pderksen** [comment]
@sarjona Also thanks for submitting.

I'll need some time to review the grouped calendar/taxonomies change. Maybe an example screencast and/or screenshots would help display your scenario.

For the localization file, `load_plugin_textdomain` is in fact called with the `plugins_loaded` action hook, it just resides in a different function (in turn called by the class constructor).

https://github.com/moonstonemedia/Simple-Calendar/blob/4440624fdee6151290d2cc759e6ad83384955458/includes/main.php#L188-L211

**Comment by sarjona** [comment]
@pderksen You're wellcome!! :-)

- Without the "non-deadlock" patches:
1. The user can create 2 different grouped calendars and call one from the other and viceversa, like you can see in the following screenshots: http://www.screencast.com/t/bdISH2qhJ and http://www.screencast.com/t/mQPugdOLQD Our patch exclude grouped calendars of the manual selection list.
2. With the categories happens something similar: you can add some category to a grouped calendar (for instance Category1), and then configure the grouped calendar to load: http://www.screencast.com/t/g9qIkui3 Our patch don't let to select categories for grouped calendars.

- We've seen the code you said us but, in our case, is not working. Strings in other languages are only loaded with our patch :-( If you need to testing it, you can download our catalan .po and .mo files from https://github.com/projectestac/wordpress-gce/tree/master/i18n

**Comment by pderksen** [comment]
@sarjona Sorry for the delay. We're still backlogged with projects. We're hoping to address this next week sometime at this point.

**Comment by roxaubrey** [comment]
Using this plugin because it's GREAT, however, when I hover over an event, the window shows up super low on my screen and is cut off. I apologize for being a noob, but is there an adjustment I can make in the CSS? I've tried everything I know (which isn't much) and nothing has worked.

**Comment by nickyoung87** [comment]
@roxaubrey We already have that issue documented at #221 Please post on that issue and not this pull request.

**Comment by cliffordp** [comment]
`load_plugin_textdomain` is not needed if you let translate.wordpress.org do the translations _and_ you change the readme.txt header's `Requires at least:` to `4.6`, per https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#loading-text-domain

**Pull request closed without merging**
